winutil:
  enabled: true
  script_local_path: '{{ role_path }}/files/winutil.ps1'
  script_url: 'https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1'
  script_checksum: ''
  tweaks_config_src: winutil_tweaks.json
